# Generated by Django 4.2.16 on 2024-10-24 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://order.foodworks.org/assets/img/foodworks/default-menu-image-placeholder.png', max_length=500),
        ),
    ]
